# Generated by Django 5.1.4 on 2024-12-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='window_type',
            field=models.CharField(choices=[('new window', '--new-window'), ('current window', 'Current Window')], default='new window', max_length=50),
        ),
    ]
