# Generated by Django 5.1.4 on 2024-12-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_program_window_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='project_path',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Project Path'),
        ),
        migrations.AddField(
            model_name='program',
            name='project_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Project Type'),
        ),
    ]
